### ISSUE TITLE
Update spreedme version?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/spreedme-snap#11]
@oparoz 0.3.5 is released, does the snap handle this automatically or do we need to change version number?

https://github.com/strukturag/nextcloud-spreedme/releases

**Comment by oparoz** [comment]
A merged PR should be enough to generate new snaps ready to be tested.

**Comment by enoch85** [comment]
I'm happy to make a PR if you tell me what to change...

**Comment by oparoz** [comment]
https://github.com/nextcloud/spreedme-snap/blob/master/snapcraft.yaml#L2
and
https://github.com/nextcloud/spreedme-snap/blob/master/snapcraft.yaml#L20
and
https://github.com/nextcloud/spreedme-snap/blob/master/snapcraft.yaml#L29

**Comment by oparoz** [comment]
Updated to 0.29.5 and 0.3.6
