### ISSUE TITLE
Use this snap with the nextcloud vm

### ISSUE THREAD

**Issue by enoch85** [nextcloud/spreedme-snap#7]
Hey guys, was thinking we could use this snap for the Nextcloud VM. Is it stable? Can't find it in the Ubuntu repo... is it even released yet?

**Comment by oparoz** [comment]
It's stable, but I just need to push a minor cosmetic change and merge the PR.

You simply need to add those changes to the VM
https://github.com/nextcloud/nextcloud-snap/pull/72/files

and to follow the instructions
https://help.nextcloud.com/t/spreed-me-snap-for-the-nextcloud-snap-beta/3757

**Comment by oparoz** [comment]
But you could also use the Docker, no? Since you're already using Docker for Collabora

**Comment by enoch85** [comment]
Cool, I'll look into this later. 

We are not using either Collabora or any other Docker either atm, but it would be an easy fix to just add this snap or something similar instead of writing the scripts from start. Also, it would be a good reason for me to maintain this build.

**Comment by oparoz** [comment]
OK. I'll let you know once it's in the store

**Comment by oparoz** [comment]
Snap is now available in the snap store.

**Comment by enoch85** [comment]
Cool, just tested and it works. Will try to separate the vhosts and see if that works. Would be cool to script the whole install with this snap. 

One thing that I wonder is that it says that I have to create a new user, but where do I do that?

Btw, are there any way to generate the config from a shell command?

**Comment by oparoz** [comment]
> One thing that I wonder is that it says that I have to create a new user, but where do I do that?

Where did you read that?

> Btw, are there any way to generate the config from a shell command?

Not that I know of, but @longsleep and @leonklingele should know

**Comment by enoch85** [comment]
@oparoz IRC pls :)

**Comment by enoch85** [comment]
JFTR: 
![deepinscreenshot20161016191557](https://cloud.githubusercontent.com/assets/4511254/19419297/fe1aa00a-93d4-11e6-8eb0-3f2fc54c705a.png)

**Comment by oparoz** [comment]
You need to restart the service

**Comment by enoch85** [comment]
Tried everything nothing works... This seems to be a bug actually.

And btw, would be great if it could be possible to generate a SpreeMe Config from CLI to be able to copy the secret to the server.conf.

**Comment by enoch85** [comment]
Ok, finnally got it working by generating a new key several times. Still, it would be nice to do this via CLI for automated installs. Maybe a PHP command?

**Comment by oparoz** [comment]
> Ok, finnally got it working by generating a new key several times

That sucks :(

> And btw, would be great if it could be possible to generate a SpreeMe Config from CLI to be able to copy the secret to the server.conf.

Please open a feature request in the Nextcloud plugin repo :)

**Comment by enoch85** [comment]
This is done so I'll close.

Added my wishes here: https://github.com/strukturag/nextcloud-spreedme/issues/36#issuecomment-254086479
