### ISSUE TITLE
Where to find the Nextcloud vhost config?

### ISSUE THREAD

**Issue by nephilim75** [nextcloud/spreedme-snap#9]
Hello

it is really embarrassing but I don't find the vhost config for Nextcloud to adapt the required reverse proxy changes.

Kind regards
//neph

**Comment by oparoz** [comment]
It's in the readme, but I need to add the information for NGINX as well.

**Comment by nephilim75** [comment]
I read it but cannot find the path to the Apache vhost configuration.

> "You need to configure your reverse proxy so that Nextcloud can communicate with the snap
> 
> Apache
> 
> Make sure the following modules are installed
> 
> mod_proxy
> mod_proxy_http
> mod_proxy_wstunnel
> Add an entry in your Nextcloud virtualhost which points the /webrtc directory to the Spreed.ME snap."

I can see what to do and what do add to the config but not the location oft the mentioned vhost config file.

**Comment by oparoz** [comment]
> I read it but cannot find the path to the Apache vhost configuration.

That file is where your distribution or your sysadmin has put it. It has nothing to do with this snap.
